# Generated by Django 4.2.4 on 2023-08-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=10)),
                ('cjob', models.CharField(max_length=20)),
                ('cbranch', models.CharField(max_length=30)),
                ('cbalance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
